[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "util"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.51"
itertools = "0.10.1"
pathfinding = "3.0.9"
